src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

use App\Entity\Traits\Timestampable;
use phpDocumentor\Reflection\DocBlock\Tag;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


use Doctrine\Common\Collections\ArrayCollection;


#[ORM\Entity(repositoryClass: VoitureRepository::class)]
#[ORM\Table(name: "voitures")]
#[ORM\HasLifecycleCallbacks]

#[Vich\Uploadable]
class Voiture
{
    use Timestampable;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Insérez votre nom")]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Insérez  une marque")]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Insérez une couleur")]
    private ?string $couleur = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Entrez l'année")]
    #[Assert\Length(exactly: 4, exactMessage: "Vous devez avoir un maximum de 4 chiffres")]
    private ?int $annee = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Entrez le prix")]
    private ?float $prix = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $imageName = "voiture.jpeg";


    #[Vich\UploadableField(mapping: 'users', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\ManyToOne(inversedBy: 'voitures')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: User::class)]
    #[ORM\JoinTable('user_voiture_Like')]
    private $like;

    public function __construct()
    {
        $this->like = new ArrayCollection();
    }
    public function getLikes()
    {
        return $this->like;
    }
    public function addLike(User $like): self
    {
        if (!$this->like->contains($like)) {
            $this->like[] = $like;
        }
        return $this;
    }
    public function removelike(User $like): self
    {
        $this->like->removeElement($like);
        return $this;
    }

    public function isLikedByUser(User $user): bool
    {
        return $this->like->contains($user);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(?string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(?string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->annee;
    }

    public function setAnnee(?int $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }



    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }
    /**
     * Return only the security relevant data
     *
     * @return array
     */
    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'nom' => $this->nom,
            'couleur' => $this->couleur,
        ];
    }
}

templates/layouts/partials/_footer.html.twig
<div class="b-example-divider"></div>

<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="{{ path('app_voiture_index') }}" class="nav-link px-2 text-body-secondary">Home</a></li>
      {# <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li> #}
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">&copy; 2023 Cfitech, Inc</p>
  </footer>
</div>

templates/layouts/partials/_jumbotrons.html.twig
<div class="container my-5">
  <div class="position-relative p-5 text-center text-muted bg-body border border-dashed rounded-5 bg-success-subtle">

  
    <h1 class="text-body-emphasis">Welcome</h1>
    <h3><p class="col-lg-6 mx-auto mb-4">
      Do you want to buy or sell a car? You are in the right place. The car of your dreams is a click away
    </p></h3>
    {# <a class="btn btn-primary px-5 mb-5" type="button"  href="{{ path('app_register')}}">
     Create your account
    </a> #}

  </div>
</div>

templates/layouts/partials/_like.html.twig
<div class="p-3">
	<div class="flex">
		{% if app.user %}
			<a class="flex w-fit" href="{{ path('like_voiture', {id: voiture.id}) }}" data-action="like" data-nb={{ voiture.likes|length }}>
			{% endif %}

			<svg xmlns="http://www.w3.org/2000/svg" class="h-2 w-2 filled {{ app.user in voiture.likes ? '' : 'hidden' }}" viewbox="0 0 20 20" fill="currentColor">
				<path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z"/>
			</svg>
			<svg xmlns="http://www.w3.org/2000/svg" class="h-2 w-2 unfilled {{ app.user in voiture.likes ? 'hidden' : '' }}" fill="none" viewbox="0 0 24 24" stroke="currentColor" stroke-width="2">
				<path stroke-linecap="round" stroke-linejoin="round" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5"/>
			</svg>

			<span class="ml-2">{{ voiture.likes|length }}
				Like </span>
			{% if app.user %}
			</a>
		{% endif %}
	</div>
</div>

templates/layouts/partials/_nav.html.twig
 <nav class="navbar navbar-expand-lg bg-body-tertiary rounded" aria-label="Thirteenth navbar example">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
<div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
          <a class="navbar-brand col-lg-3 me-0" href="{{ path('app_voiture_index') }}">Magasin Voiture</a>
          <ul class="navbar-nav col-lg-6 justify-content-lg-center">
           {% if app.user %} 
            {% if app.user.isVerified %} 
            <li class="nav-item">
              <a class="nav-link " aria-current="page" href="{{ path('app_voiture_creer') }}">Creer Voiture </a>
            </li>
             {% endif %}
             <li class="nav-item">
              <a class="nav-link" href="{{ path('app_account') }}">Account</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ path('app_register') }}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{{ path('app_login') }}">Login</a>
            </li>
           
            {% endif %}
            {# <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>#}
           {# <div class="d-lg-flex col-lg-6 justify-content-lg-end">
            <button class="btn btn-primary">Button</button>
          </div>  #}
        </div>
      </div>
    </nav>

templates/layouts/partials/_search_data.html.twig
{% if form %}
    {{ form_start(form) }}
    <div class="flex justify-center">
        <div class="mb-3 xl:w-96">
            <div class="input-group relative flex flex-wrap items-stretch w-full mb-4">
                {{ form_widget(form.q, {'attr': {'class': 'form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none'}}) }}

                <button class="btn inline-block px-6 py-2.5 bg-blue-600 text-white font-medium 
                text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 
                hover:shadow-lg focus:bg-blue-700  focus:shadow-lg focus:outline-none focus:ring-0 
                active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out 
                flex items-center" type="submit" id="button-addon2">

                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" 
                    class="w-4" role="img" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512">
                        <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>
    {{ form_end(form) }}
{% endif %}

templates/layouts/partials/_slidebar.html.twig
 
 
 
 
 <div class="d-flex flex-column align-items-stretch flex-shrink-0 border border-dashed rounded-5  " style="width: 250px;">
    <a href="/" class="d-flex align-items-center flex-shrink-0 p-3 link-body-emphasis text-decoration-none ">
      <svg class="bi pe-none me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
     <h1> <strong class="mb-1">You might find it interesting</strong></h1>
    </a>
    <div class="list-group list-group-flush  scrollarea">
      <a href="https://www.promopromo.be/nl" class="list-group-item list-group-item-action  py-3 lh-sm" >
        <div class="d-flex w-100 align-items-center justify-content-between">
        <img src="https://media.istockphoto.com/photos/percentage-sign-picture-id182178918?k=6&m=182178918&s=612x612&w=0&h=Ki4QSpD8_OOxH_3StdH1qVO_CLkM3QaDBHNhPvb9YB4=" style="width: 150px;" >
         
          
        </div>
       
      </a>
      <a href="https://www.autoscout24.be/fr/" class="list-group-item list-group-item-action py-3 lh-sm">
        <div class="d-flex w-100 align-items-center justify-content-between">
          <img src="https://th.bing.com/th/id/R.90881e0bc57a8330999f5b037a47092c?rik=3Pa9udv9uRrcAA&pid=ImgRaw&r=0" style="width: 150px;">
         
        </div>
      
      </a>
      <a href="https://www.amazon.fr/?tag=hydfrabkm-21&ref=pd_sl_781ozcfkwe_e&adgrpid=1362295842742589&hvadid=85143748759658&hvnetw=o&hvqmt=e&hvbmt=be&hvdev=c&hvlocint=&hvlocphy=609&hvtargid=kwd-85144014621571:loc-14&hydadcr=11802_1930447" class="list-group-item list-group-item-action py-3 lh-sm">
        <div class="d-flex w-100 align-items-center justify-content-between">
         <img src="https://nypost.com/wp-content/uploads/sites/2/2020/04/amazon-feature.jpg?quality=90&strip=all&w=744" style="width: 150px;">
        </div>
        
      </a>

      <a href="https://www.bol.com/be/fr/" class="list-group-item list-group-item-action py-3 lh-sm" aria-current="true">
        <div class="d-flex w-100 align-items-center justify-content-between">
         <img src="https://th.bing.com/th/id/R.af9db9700fc5633ed3eb706387ef636d?rik=D4OEYm4X0Y2WRA&pid=ImgRaw&r=0" style="width: 150px;">
        </div>
        
      </a>
      <a href="https://www.tikamoon.com/?utm_id=408008629&msclkid=834c2277071e1ca50f0246e675309e9a&utm_source=bing&utm_medium=cpc&utm_campaign=%5BSearch%5D%20G%C3%A9n%C3%A9rique&utm_term=meuble&utm_content=G%C3%A9n%C3%A9rique_Meuble" class="list-group-item list-group-item-action py-3 lh-sm">
        <div class="d-flex w-100 align-items-center justify-content-between">
         <img src="https://th.bing.com/th/id/OIP.x2EogV0OCfA-X2JM4mHA-AHaEc?pid=ImgDet&rs=1" style="width: 150px;">
        </div>
       
      </a>
      <a href="https://www.canva.com/" class="list-group-item list-group-item-action py-3 lh-sm">
        <div class="d-flex w-100 align-items-center justify-content-between">
        <img src="https://berghconsulting.com/wp-content/uploads/2021/04/Copy-of-Name-of-Video_Question-6.png" style="width: 150px;">
        </div>
       
      </a>
  
   
     
      {# <a href="#" class="list-group-item list-group-item-action py-3 lh-sm" aria-current="true">
        <div class="d-flex w-100 align-items-center justify-content-between">
          <strong class="mb-1">List group item heading</strong>
          <small class="text-body-secondary">Wed</small>
        </div>
        <div class="col-10 mb-1 small">Some placeholder content in a paragraph below the heading and date.</div>
      </a> #}
      {# <a href="#" class="list-group-item list-group-item-action py-3 lh-sm">
        <div class="d-flex w-100 align-items-center justify-content-between">
          <strong class="mb-1">List group item heading</strong>
          <small class="text-body-secondary">Tues</small>
        </div>
        <div class="col-10 mb-1 small">Some placeholder content in a paragraph below the heading and date.</div>
      </a> #}
      {# <a href="#" class="list-group-item list-group-item-action py-3 lh-sm">
        <div class="d-flex w-100 align-items-center justify-content-between">
          <strong class="mb-1">List group item heading</strong>
          <small class="text-body-secondary">Mon</small>
        </div> #}
        {# <div class="col-10 mb-1 small">Some placeholder content in a paragraph below the heading and date.</div> #}
      </a>
    </div>
  </div>